name: Gradle Build And Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check Build And Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Build with Gradle️
        run: ./gradlew build --stacktrace

      - name: Run Tests
        run: ./gradlew testDebugUnitTest